const usersSeed = [
  {
    username: "admin",
    fullName: "System Administrator",
    email: "admin@alpha-queue.local",
    role: "Admin",
    department: "CCM",
    phone: "+966 50 000 0001",
    restricted: false,
    standing: "Staff",
    printing: {
      quota: {
        remaining: 500,
      },
    },
    password: "12345678",
  },
  {
    username: "subadmin",
    fullName: "Quota Manager",
    email: "subadmin@alpha-queue.local",
    role: "SubAdmin",
    department: "CCM",
    phone: "+966 50 000 0002",
    restricted: false,
    standing: "Staff",
    printing: {
      quota: {
        remaining: 250,
      },
    },
    password: "12345678",
  },
  {
    username: "202279720",
    fullName: "Mohammed Alshammasi",
    email: "mohammed@kfupm.edu.sa",
    role: "User",
    department: "Software Engineering",
    phone: "+966 5X XXX XXXX",
    restricted: false,
    standing: "Senior",
    printing: {
      quota: {
        remaining: 24.5,
      },
    },
    password: "12345678",
  },
  {
    username: "202322750",
    fullName: "Ali Alorud",
    email: "202322750@kfupm.edu.sa",
    role: "User",
    department: "Software Engineering",
    phone: "+966 50 111 2233",
    restricted: true,
    standing: "Junior",
    printing: {
      quota: {
        remaining: 50,
      },
    },
    password: "12345678",
  },
];

const printersSeed = [
  {
    name: "HP LaserJet 401",
    model: "HP LaserJet 401",
    location: "Building 22, Room 122",
    building: "Building 22",
    room: "122",
    department: "CCM",
    status: "Online",
    capabilities: ["Duplex", "B&W", "Secure Release"],
    totalPagesPrinted: 12400,
    totalJobsSubmitted: 890,
    costPerPage: 0.05,
    ipAddress: "10.10.22.41",
    queueName: "secure-release-b22-122",
    serialNumber: "HP401-KFUPM-001",
    deviceType: "Physical",
    tonerLevel: 78,
    paperLevel: 64,
    notes: "Main student lab printer.",
  },
  {
    name: "Canon C5535i",
    model: "Canon C5535i",
    location: "Building 22, Room 214",
    building: "Building 22",
    room: "214",
    department: "CCM",
    status: "Online",
    capabilities: ["Duplex", "Color", "B&W", "Secure Release", "Scan", "Copy"],
    totalPagesPrinted: 10200,
    totalJobsSubmitted: 750,
    costPerPage: 0.05,
    ipAddress: "10.10.22.52",
    queueName: "secure-release-b22-214",
    serialNumber: "CAN5535-KFUPM-002",
    deviceType: "Physical",
    tonerLevel: 66,
    paperLevel: 71,
    notes: "Supports color and scanning.",
  },
  {
    name: "Xerox 7855",
    model: "Xerox 7855",
    location: "Building 23, Room 311",
    building: "Building 23",
    room: "311",
    department: "CCM",
    status: "Low Toner",
    capabilities: ["Color", "B&W", "Copy"],
    totalPagesPrinted: 8900,
    totalJobsSubmitted: 620,
    costPerPage: 0.04,
    ipAddress: "10.10.23.17",
    queueName: "faculty-b23-311",
    serialNumber: "XRX7855-KFUPM-003",
    deviceType: "Physical",
    tonerLevel: 14,
    paperLevel: 83,
    notes: "Needs toner replacement soon.",
  },
];

const queuesSeed = [
  {
    name: "Faculty Secure Queue",
    description: "Secure release queue for faculty members",
    type: "Secure Release",
    status: "Active",
    assignedPrinters: ["HP LaserJet 401", "Canon C5535i"],
    defaultPrinter: "HP LaserJet 401",
    allowedRoles: ["User", "SubAdmin", "Admin"],
    allowedGroups: ["Faculty Group"],
    allowedDepartments: ["Computer Science", "Engineering"],
    restrictedUsers: [],
    pendingJobs: 7,
    retentionHours: 24,
    secureRelease: true,
    manualReleaseRequired: false,
    allowReleaseAllJobs: true,
    requirePrinterAuthentication: true,
    autoDeleteExpiredJobs: true,
  },
  {
    name: "Engineering Department Queue",
    description: "Daily printing queue for engineering students",
    type: "Faculty",
    status: "Active",
    assignedPrinters: ["HP LaserJet 402", "Xerox 7855"],
    defaultPrinter: "HP LaserJet 402",
    allowedRoles: ["User"],
    allowedGroups: ["Engineering Group"],
    allowedDepartments: ["Engineering"],
    restrictedUsers: [],
    pendingJobs: 14,
    retentionHours: 12,
    secureRelease: false,
    manualReleaseRequired: false,
    allowReleaseAllJobs: false,
    requirePrinterAuthentication: false,
    autoDeleteExpiredJobs: true,
  },
  {
    name: "Student Secure Queue",
    description: "Secure queue for student shared areas",
    type: "Secure Release",
    status: "Inactive",
    assignedPrinters: ["Ricoh MP 5002", "Canon C3530i"],
    defaultPrinter: "Ricoh MP 5002",
    allowedRoles: ["User"],
    allowedGroups: ["Student Group"],
    allowedDepartments: ["Business", "Engineering"],
    restrictedUsers: [],
    pendingJobs: 5,
    retentionHours: 24,
    secureRelease: true,
    manualReleaseRequired: false,
    allowReleaseAllJobs: true,
    requirePrinterAuthentication: true,
    autoDeleteExpiredJobs: true,
  },
];

const quotaTransactionsSeed = [
  {
    userUsername: "202279720",
    type: "Credit addition",
    amount: 50,
    quotaAfter: 50,
    comment: "Monthly credit allocation",
    reference: "ALLOC-APR-2026",
    method: "System",
  },
  {
    userUsername: "202279720",
    type: "Print deduction",
    amount: -18.5,
    quotaAfter: 31.5,
    comment: "Print order payment",
    reference: "JOB-002",
    method: "Auto Deduction",
  },
  {
    userUsername: "202279720",
    type: "Print deduction",
    amount: -7,
    quotaAfter: 24.5,
    comment: "Print order payment",
    reference: "JOB-003",
    method: "Auto Deduction",
  },
  {
    userUsername: "202279720",
    type: "Refund",
    amount: 3.5,
    quotaAfter: 28,
    comment: "Auto refund for failed job",
    reference: "JOB-FAILED-004",
    method: "System",
  },
];

const printJobsSeed = [
  {
    userUsername: "202279720",
    printerName: "HP LaserJet 401",
    queueName: "Faculty Secure Queue",
    jobId: "job-001",
    documentName: "thesis_final_v3.pdf",
    pages: 24,
    cost: 2.4,
    status: "Pending Release",
    attributes: ["PDF", "Black & White", "Duplex"],
    clientSource: "Web Print",
    fileType: "PDF",
    printMode: "Black & White · Duplex",
    readinessPercent: 100,
  },
  {
    userUsername: "202279720",
    printerName: "Canon C5535i",
    queueName: "Faculty Secure Queue",
    jobId: "job-002",
    documentName: "slides_ch4.pptx",
    pages: 12,
    cost: 1.2,
    status: "Printed",
    attributes: ["PPTX", "Color", "Single-sided"],
    clientSource: "Windows Client",
    fileType: "PPTX",
    printMode: "Color · Single-sided",
    readinessPercent: 100,
  },
  {
    userUsername: "202279720",
    printerName: "HP LaserJet 401",
    queueName: "Student Secure Queue",
    jobId: "job-003",
    documentName: "assignment_math.pdf",
    pages: 4,
    cost: 0.4,
    status: "Pending Release",
    attributes: ["PDF", "Color", "Single-sided"],
    clientSource: "Web Print",
    fileType: "PDF",
    printMode: "Color · Single-sided",
    readinessPercent: 82,
  },
  {
    userUsername: "202279720",
    printerName: "Xerox 7855",
    queueName: "Engineering Department Queue",
    jobId: "job-004",
    documentName: "report_draft.docx",
    pages: 8,
    cost: 0.8,
    status: "Failed",
    attributes: ["DOCX", "Black & White", "Single-sided"],
    clientSource: "Windows Client",
    fileType: "DOCX",
    printMode: "Black & White · Single-sided",
    readinessPercent: 100,
  },
  {
    userUsername: "202279720",
    printerName: "Xerox 7855",
    queueName: "Engineering Department Queue",
    jobId: "job-005",
    documentName: "report_draft.docx",
    pages: 8,
    cost: 0.8,
    status: "Refunded",
    attributes: ["DOCX", "Black & White", "Single-sided"],
    clientSource: "System Refund",
    fileType: "DOCX",
    printMode: "Black & White · Single-sided",
    readinessPercent: 100,
  },
];

module.exports = {
  usersSeed,
  printersSeed,
  queuesSeed,
  quotaTransactionsSeed,
  printJobsSeed,
};
